### ISSUE TITLE
关于磨损均衡相关问题

### ISSUE THREAD

**Issue by lmnbvcxz1** [nickfox-taterli/nor_flash_wl#1]
我在使用DEMO的过程中发现 WL_Flash_Erase_Range 函数中并没有物理地址和虚拟地址的转换，每次写入和读出的物理地址都一样，是如何做到磨损均衡的？

**Comment by jashawnyu** [comment]
哈哈，老哥牛皮呢，

**Comment by ChenXJzz** [comment]
怎么解决的，实测发现WL_Flash_Erase_Range 非常耗时间，而且是阻塞的，导致程序无法运行，且并没有磨损均衡
